all:
  hosts:
    decentralized:
      ansible_host: 5.161.161.161
      ansible_user: root
    manager_1:
      ansible_host: 5.161.161.161
      ansible_user: root
#    manager_2:
#      ansible_host: 5.161.161.161
#      ansible_user: root
#    manager_3:
#      ansible_host: 5.161.161.161
#      ansible_user: root
    worker_1:
      ansible_host: 5.161.161.161
      ansible_user: root
    worker_2:
      ansible_host: 5.161.161.161
      ansible_user: root
    worker_3:
      ansible_host: 5.161.161.161
      ansible_user: root

db:
  hosts:
    decentralized:

other_managers:
  hosts:
#    manager_2:
#    manager_3:

leader:
  hosts:
    manager_1:

workers:
  hosts:
    worker_1:
    worker_2:
    worker_3:

swarm:
  hosts:
    manager_1:
#    manager_2:
#    manager_3:
    worker_1:
    worker_2:
    worker_3:
