---
domain: domain.com
leader_address: 10.1.0.4

# Database
## it's best to use internal IP for the mysql_ip value
mysql_ip: 10.1.0.2
mysql_user: appwrite
mysql_database: appwrite
mysql_password: password
mysql_root_password: password_root

# SSL Keys
## This cannot be generated at runtime as there is more the one server.
ssl_key: set_256_random_string
executor_secret: set_32_random_string

# Swap file
swap_file: /swapfile
swap_size: 4G