version: '3'

services:
  mariadb:
    image: mariadb:10.7
    container_name: appwrite-mariadb
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - gateway
    volumes:
      - appwrite-mariadb:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    command: 'mysqld --innodb-flush-method=fsync'

  redis:
    image: redis:7.0.4-alpine
    container_name: appwrite-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      redis-server
      --maxmemory            512mb
      --maxmemory-policy     allkeys-lru
      --maxmemory-samples    5
    networks:
      - gateway
    volumes:
      - appwrite-redis:/data:rw

  influxdb:
    image: appwrite/influxdb:1.5.0
    container_name: appwrite-influxdb
    restart: unless-stopped
    networks:
      - gateway
    ports:
      - "8086:8086"
    volumes:
      - appwrite-influxdb:/var/lib/influxdb:rw

networks:
  gateway:

volumes:
  appwrite-mariadb:
    driver: local
    driver_opts:
      type: volume
      o: "bind"
      device: "/home/share/mariadb"
  appwrite-redis:
    driver: local
    driver_opts:
      type: volume
      o: "bind"
      device: "/home/share/redis"
  appwrite-influxdb:
    driver: local
    driver_opts:
      type: volume
      o: "bind"
      device: "/home/share/influxdb"
